replicaCount: 2

image:
  repository: prvnv7/springboot
  pullPolicy: IfNotPresent
  # Override the app's default port if necessary
  port: 8080

service:
  type: NodePort
  port: 8080

# Other configurations can remain default for now
