name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: prvnv7/springboot:1.0.0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install and configure kubectl
      uses: azure/setup-kubectl@v1

    - name: Set up kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $GITHUB_WORKSPACE/.kubeconfig
      env:
        KUBECONFIG: $GITHUB_WORKSPACE/.kubeconfig

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.6.0'

    - name: Deploy with Helm
      run: |
        kubectl config view --minify --output 'jsonpath={..server}'
        helm upgrade --install weatherservice-release ./weatherservice --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig
        kubectl rollout status deployment/weatherservice-release

